# Clase 09 — Ejercicio intergrador Clínica MediCare

> Notebook de práctica. Ejecutá las celdas a medida que avanzás en el artículo.

La clínica MediCare lleva varios años registrando turnos médicos en un sistema interno. El sistema fue cambiando de versión con el tiempo, y los datos se fueron exportando a una base de datos SQLite sin demasiado control de calidad.

El director médico necesita un informe con algunas preguntas concretas sobre el funcionamiento de la clínica, pero antes de poder responderlas, alguien tiene que hacer la limpieza. Ese trabajo es el de ustedes, no se les dice qué problemas hay en los datos. Parte del ejercicio es encontrarlos.

> El archivo de la base de datos `medicare.db` ya está disponible para que lo uses en este ejercicio.

### 1) Exploración: ¿qué tiene esta base de datos?

Antes de tocar nada, el primer trabajo es entender qué hay adentro. Conectense a `medicare.db` y respondan estas preguntas.

1. ¿Qué tablas tiene la base de datos?
2. ¿Qué columnas y tipos tiene cada tabla?
3. ¿Cuántas filas tiene cada tabla?

In [1]:
#instalacion de pandas
pip install pandas

SyntaxError: invalid syntax (1300835869.py, line 2)

In [ ]:
#importo sqlite3 y pandas 
import sqlite3
import pandas as pd

#conexion 
conexion = sqlite3.connect("medicare.db")

df = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", conexion)


df_pacientes = pd.read_sql("SELECT * FROM pacientes", conexion)
df_medicos = pd.read_sql("SELECT * FROM medicos", conexion)
df_turnos = pd.read_sql("SELECT * FROM turnos", conexion)

#Cierro conexion 
conexion.close()

df_pacientes

,id,nombre,dni,fecha_nacimiento,ciudad,obra_social
0,1,Martina García,28.341.992,1985-04-12,Buenos Aires,OSDE
1,2,Roberto Díaz,31.882.441,1990-11-30,Córdoba,Swiss Medical
2,3,Luciana Pérez,35.112.008,2001-07-22,NaN,PAMI
3,4,Martina García,28.341.992,1985-04-12,Buenos Aires,OSDE
4,5,Tomás Ruiz,40.223.117,2000-03-15,Rosario,NaN
...,...,...,...,...,...,...
61,62,Daniela Suárez,27.742.735,1961-03-08,NaN,Galeno
62,63,Ignacio Sánchez,24.037.826,1970-11-17,Bahía Blanca,NaN
63,64,Milagros López,39.156.684,2002-11-06,Rosario,Galeno
64,65,Lucas Castro,32.279.328,NaN,Bahía Blanca,NaN
65,66,Agustina Ruiz,36.376.846,1979-08-16,La Plata,Swiss Medical

In [ ]:
df_pacientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                66 non-null     int64
 1   nombre            66 non-null     str
 2   dni               59 non-null     str
 3   fecha_nacimiento  55 non-null     str
 4   ciudad            58 non-null     str
 5   obra_social       54 non-null     str
dtypes: int64(1), str(5)
memory usage: 3.2 KB

In [ ]:
df_medicos

    id               nombre    especialidad matricula activo
0    1    Dra. Beatriz Sosa  Clínica Médica  MP-12345      1
1    2     Dr. Nicolás Vera       Pediatría  MP-23456      1
2    3  Dra. Carmen Aguirre     Cardiología       NaN      1
3    4     Dr. Pablo Méndez  Clínica Médica  MP-45678      0
4    5    Dra. Beatriz Sosa  Clínica Médica  MP-12345      1
5    6   Dr. Sebastián Ríos   Traumatología  MP-56789      1
6    7   Dra. Laura Giménez       Pediatría  MP-67890    NaN
7    8    Dra. Beatriz Sosa      Neurología  MP-21073      0
8    9     Dr. Nicolás Vera  Endocrinología  MP-46953    NaN
9   10  Dra. Carmen Aguirre   Traumatología  MP-15929      0
10  11     Dr. Pablo Méndez     Cardiología  MP-68435      1
11  12   Dr. Sebastián Ríos    Dermatología  MP-53113    NaN
12  13   Dra. Laura Giménez     Ginecología  MP-50573      1
13  14   Dra. Andrea Blanco     Ginecología  MP-53952      0
14  15     Dr. Martín Cufré       Pediatría  MP-75898      1
15  16    Dra. Verónica Paz   Traumatología  MP-10648      1
16  17     Dr. Hernán Costa    Dermatología  MP-28856      0
17  18   Dra. Gabriela Luna     Psiquiatría       NaN      1
18  19   Dr. Ezequiel Bravo    Dermatología  MP-40514      1
19  20    Dra. Silvina Vega     Psiquiatría  MP-30349    NaN

In [ ]:
df_medicos.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            20 non-null     int64
 1   nombre        20 non-null     str
 2   especialidad  20 non-null     str
 3   matricula     18 non-null     str
 4   activo        16 non-null     str
dtypes: int64(1), str(4)
memory usage: 932.0 bytes

In [ ]:
df_turnos

,id,paciente_id,medico_id,fecha,hora,motivo,costo,estado
0,1,1,1,2024-03-01,09:00,Control anual,3500,realizado
1,2,2,2,2024-03-01,10:30,Fiebre,4200,realizado
2,3,3,1,2024-03-02,08:30,Dolor abdominal,3500,realizado
3,4,4,3,2024-03-02,11:00,Electrocardiograma,8500,realizado
4,5,5,2,2024-03-03,NaN,Control pediátrico,4200,realizado
...,...,...,...,...,...,...,...,...
205,206,47,3,2024-04-09,09:30,Dolor rodilla,8500,realizado
206,207,21,17,2024-04-07,11:15,Estudio de rutina,9200,realizado
207,208,46,19,2024-03-06,08:00,Esguince tobillo,8500,pendiente
208,209,51,4,2024-05-15,NaN,Control anual,6800,cancelado
209,210,35,18,2024-05-05,17:15,Estudio de rutina,4200,pendiente

In [ ]:
df_turnos.info()

<class 'pandas.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           210 non-null    int64
 1   paciente_id  210 non-null    int64
 2   medico_id    210 non-null    int64
 3   fecha        210 non-null    str
 4   hora         194 non-null    str
 5   motivo       194 non-null    str
 6   costo        201 non-null    str
 7   estado       210 non-null    str
dtypes: int64(3), str(5)
memory usage: 13.3 KB

In [ ]:
# 1 la base de datos contiene 3 tablas (pacientes,medicos turnos)
# 2 cada tabla tiene datos de tipo str , enteros y nulos 
# 3 tien 66 pacients , 20 medicos y 210 turnos

**Documenten sus hallazgos.** Antes de seguir al Paso 2, escriban en comentarios qué encontraron.

### 2) Diagnóstico: ¿qué problemas tienen los datos?

Traigan las tres tablas a DataFrames y hagan un diagnóstico completo de cada una. Para cada tabla respondan:

- ¿Cuántos nulos hay por columna? ¿Qué porcentaje representan?
- ¿Hay filas duplicadas? ¿Cuáles?
- ¿Hay columnas con tipos incorrectos que van a impedir operar con los datos?
- ¿Hay valores que parecen errores aunque no sean nulos? (Pista: revisen la columna `costo` en `turnos`)

In [ ]:
#analizo los null de la tabla pacientes 

cantida_nulos_pacientes= df_pacientes.isnull().sum()
porcentaje_nulos_pacientes =((cantida_nulos_pacientes / len(df_pacientes)) * 100).round(2)

print(porcentaje_nulos_pacientes.map("{:.2f}%".format))

id                   0.00%
nombre               0.00%
dni                 10.61%
fecha_nacimiento    16.67%
ciudad              12.12%
obra_social         18.18%
dtype: str

In [ ]:
#analizo los null de la tabla medicos

cantida_nulos_medicos= df_medicos.isnull().sum()
porcentaje_nulos_medicos =((cantida_nulos_medicos / len(df_medicos)) * 100).round(2)

print(porcentaje_nulos_medicos.map("{:.2f}%".format))

id               0.00%
nombre           0.00%
especialidad     0.00%
matricula       10.00%
activo          20.00%
dtype: str

In [ ]:
#analizo los null de la tabla turnos

cantida_nulos_turnos= df_turnos.isnull().sum()
porcentaje_nulos_turnos = ((cantida_nulos_turnos / len(df_turnos)) * 100).round(2)

print(porcentaje_nulos_turnos.map("{:.2f}%".format))

id             0.00%
paciente_id    0.00%
medico_id      0.00%
fecha          0.00%
hora           7.62%
motivo         7.62%
costo          4.29%
estado         0.00%
dtype: str

In [ ]:
# analizo si hay duplicados en la tabla de pacientes

#
pacientes_repetidos = df_pacientes[df_pacientes.duplicated(subset=['nombre','dni'])].sum()

pacientes_repetidos

id                                                                355
nombre              Martina GarcíaRoberto DíazLuciana PérezFranco ...
dni                 28.341.99231.882.44135.112.00834.149.84822.430...
fecha_nacimiento    1985-04-121990-11-302001-07-221956-06-191975-0...
ciudad              Buenos AiresCórdobaRosarioBuenos AiresBuenos A...
obra_social         OSDESwiss MedicalPAMISwiss MedicalGalenoPAMIPA...
dtype: object

In [ ]:
#analizo si hay dattos repetidos en el df de medicos 

medicos_repetidos = df_medicos[df_medicos.duplicated(subset=['nombre','matricula'])].sum()

medicos_repetidos

id                              5
nombre          Dra. Beatriz Sosa
especialidad       Clínica Médica
matricula                MP-12345
activo                          1
dtype: object

In [ ]:
#Analizo el df de turnos si hay duplicados

turnos_repetidos = df_turnos[df_turnos.duplicated(subset=['paciente_id','medico_id','fecha','hora'])].sum()

turnos_repetidos

id                        11
paciente_id                1
medico_id                  1
fecha             2024-03-01
hora                   09:00
motivo         Control anual
costo                   3500
estado             realizado
dtype: object

**Antes de seguir al Paso 3, escriban una lista con todos los problemas que encontraron, uno por línea.** No empiecen a limpiar todavía.

In [ ]:
"""
LISTA DE PROBLEMAS DETECTADOS 

1 - existen valores NULOS  en la columna obra_social
2- existen pacientes duplicados detectados en base a los argumentos nombre y dni , excluyendo
el id primario a que va en orden ascendente y no se repite 
3- hay datos tipo str u objet en la colummna d fecha_nacimiento 
4- en el df de medicos hay datos nulos en las colummnas de matricula y activo 
5- la columna de activo tiene datos de tipo str y no booleano 
6- hay medicos duplicados  con distintos id's pero la misma matricula
7- en el df de turnos, en la columna turnos hay daatos de tipo object
8- en costo tambien se registran valores nulos a tratar
9- las columnas hora y motivo tambien presentan datos nulos
10 - hay tunos duplicados con pacientes,medicos, fecha y hora 
11- la colummna fecha son datos tipo str que no se pueden analizar
12 - en la colummna costo tambien presenta datos str 


"""

### 3) Decisiones: ¿qué hacemos con cada problema?

Este es el paso más importante del ejercicio. Para cada problema que encontraron en el Paso 2, decidan qué van a hacer y por qué. No hay una respuesta única correcta — lo que importa es que la decisión sea coherente con el análisis que necesitan hacer después.

Completen esta tabla antes de escribir código:

| Tabla | Columna | Problema | Decisión | Justificación |
|-------|---------|----------|----------|---------------|
| pacientes | fila completa | duplicados | eliminar duplicados | conteo final comprometido|
| pacientes | obra_social | 18% de nulos | rellenar con "Sin obra social" | esnecesario para un analicis sin vacios |
| pacientes | ciudad | 2nulos | rellenar"sin datos" | no se pierde info  |
| pacientes | fecha_nacimiento | tipo de dato OBJECT | convertir a datatime | se necesita tipo de dato correcto para analizar y segmentar |
| medicos | fila completa | medicos repetidos | eliminar duplicados por matricula | un profecional no puede tener 2 matriculas iguales, compromete los turnos |
| medicos | activo | 4 nulos / tipo de dato | convercio de dato a tipo booleano / relleno de nulos | optimizar filtros logicos para identificar medicos en servicio  |
| turnos | fila completa | duplicados | eliminar duplicados | un paciente no puede tener dos turnos a la vez fisicamente |
| turnos  | costo | tipo de dato / 9 nulos  | convertir a int y rellenar con 0 | es obligatorio para un resultado exato de facturacion |
| turnos | fecha | tipo dato OBJETC | converti a datatime | permite filtrar cronologicamente  |
| turnos | hora / motivo | 7.6% nulos | rellenar "sin datos" | se rellena para no perdes los demas datos importantes |
| ... | ... | ... | ... | ... |

### 4) Limpieza: aplicar las decisiones

Ahora sí, implementen las decisiones del Paso 3. Recuerden:

- Primero eliminen duplicados
- Después manejen nulos
- Después conviertan tipos

In [ ]:
# Limpieza de pacientes
df_pacientes_limpio = df_pacientes.copy()
# eliminar duplicado
df_pacientes_limpio = df_pacientes_limpio.drop_duplicates(subset=['nombre','dni'])
# rellenar 
df_pacientes_limpio['obra_social'] = df_pacientes_limpio['obra_social'].fillna('Sin Obra Social')
df_pacientes_limpio = df_pacientes_limpio.fillna('Sin Datos')
#Conversion
df_pacientes_limpio['fecha_nacimiento'] = pd.to_datetime(df_pacientes_limpio['fecha_nacimiento'], errors='coerce')


# Limpieza de médicos
df_medicos_limpio = df_medicos.copy()
# elimino duplicados
df_medicos_limpio= df_medicos_limpio.drop_duplicates(subset=['matricula'])

# Limpieza de turnos
df_turnos_limpio = df_turnos.copy()
# eliminar duplicado
df_turnos_limpio = df_turnos_limpio.drop_duplicates(subset=['paciente_id','medico_id','fecha','hora'])
#conversion 
df_turnos_limpio['costo'] = pd.to_numeric(df_turnos_limpio['costo'], errors='coerce')
df_turnos_limpio['fecha'] = pd.to_datetime(df_turnos_limpio['fecha'], errors='coerce')
#rellenar
df_turnos_limpio['costo'] = df_turnos_limpio['costo'].fillna(0)
df_turnos_limpio = df_turnos_limpio.fillna('Sin Datos')

> **Por qué `.copy()`:** cuando hacen `df_pacientes_limpio = df_pacientes`, no están creando una copia — están apuntando al mismo objeto. Cualquier cambio en `df_pacientes_limpio` modifica también `df_pacientes`. `.copy()` crea una copia independiente, así conservan los datos originales para comparar.

Al terminar, impriman un resumen de qué cambió en cada tabla:

In [ ]:
# comparacion 
print(f"Filas originales en Turnos: {len(df_turnos)}")
print(f"Filas tras limpiar duplicados: {len(df_turnos_limpio)}")
print("-" * 50)

print(f"Filas originales en Medicos: {len(df_medicos)}")
print(f"Filas tras limpiar duplicados: {len(df_medicos_limpio)}")
print("-" * 50)

print(f"Filas originales en Turnos: {len(df_pacientes)}")
print(f"Filas tras limpiar duplicados: {len(df_pacientes_limpio)}")
print("-" * 50)

Filas originales en Turnos: 210
Filas tras limpiar duplicados: 209
--------------------------------------------------
Filas originales en Medicos: 20
Filas tras limpiar duplicados: 18
--------------------------------------------------
Filas originales en Turnos: 66
Filas tras limpiar duplicados: 57
--------------------------------------------------

### 5) — Análisis: responder las preguntas del director

Con los datos limpios, respondan estas cuatro preguntas. Para cada una, combinen SQL (para traer los datos necesarios) con Pandas (para calcular o presentar el resultado):

**Pregunta 1:** ¿Cuántos turnos realizó cada médico? Mostrá el resultado ordenado de mayor a menor.

**Pregunta 2:** ¿Cuál es el costo total facturado por especialidad médica? Considerá solo los turnos con estado `'realizado'`.

**Pregunta 3:** ¿Qué obra social tiene más pacientes registrados? ¿Y cuántos pacientes no tienen obra social?

**Pregunta 4:** ¿Cuántos turnos fueron cancelados o marcados como `'ausente'`? ¿Qué médico tuvo más cancelaciones?

In [ ]:
#Pregunta 1

import sqlite3

# Volvemos a conectar con la base de datos
conexion = sqlite3.connect('medicare.db')

# cosulta
query1 = """
SELECT m.nombre, COUNT(t.id) as cantidad_turnos
FROM turnos t
JOIN medicos m ON t.medico_id = m.id
GROUP BY m.nombre
ORDER BY cantidad_turnos DESC
"""

df_ranking_actividad = pd.read_sql(query1, conexion)
df_ranking_actividad

                 nombre  cantidad_turnos
0     Dra. Beatriz Sosa               34
1    Dr. Sebastián Ríos               31
2   Dra. Carmen Aguirre               28
3      Dr. Pablo Méndez               18
4      Dr. Nicolás Vera               18
5     Dra. Silvina Vega               13
6    Dra. Laura Giménez               13
7    Dra. Gabriela Luna               11
8    Dra. Andrea Blanco               11
9    Dr. Ezequiel Bravo               10
10     Dr. Martín Cufré                9
11     Dr. Hernán Costa                9
12    Dra. Verónica Paz                5

In [ ]:
#Pregunta 2
query2 = """
SELECT m.especialidad, SUM(t.costo) as total_facturado
FROM turnos t
JOIN medicos m ON t.medico_id = m.id
WHERE t.estado = 'realizado'
GROUP BY m.especialidad
ORDER BY total_facturado DESC
"""
df_facturacion_especialidad = pd.read_sql(query2, conexion)
df_facturacion_especialidad

     especialidad  total_facturado
0     Cardiología         100800.0
1    Dermatología         100300.0
2   Traumatología          98700.0
3  Clínica Médica          75500.0
4       Pediatría          75400.0
5     Psiquiatría          41000.0
6     Ginecología          26600.0
7  Endocrinología          24700.0
8      Neurología          11000.0

In [ ]:
#pregunta 3

# Contamos las frecuencias en la columna limpia
conteo_obras = df_pacientes_limpio['obra_social'].value_counts()

print(f"Obra social con más pacientes: {conteo_obras.idxmax()}")
print(f"Pacientes sin obra social: {conteo_obras.get('Sin Obra Social', 0)}")

Obra social con más pacientes: Sin Obra Social
Pacientes sin obra social: 12

In [ ]:
# pregunta 4

# Total de turnos no concretados usando Pandas
total_no_concretados = len(df_turnos_limpio[df_turnos_limpio['estado'].isin(['cancelado', 'ausente'])])

# Médico con más cancelaciones usando SQL
query4 = """
SELECT m.nombre, COUNT(t.id) as total_cancelados
FROM turnos t
JOIN medicos m ON t.medico_id = m.id
WHERE t.estado = 'cancelado'
GROUP BY m.nombre
ORDER BY total_cancelados DESC
LIMIT 1
"""
medico_critico = pd.read_sql(query4, conexion)

#Cierro conexion 
conexion.close()

print(f"Total de turnos cancelados o ausentes: {total_no_concretados}")
print(f"El médico con más cancelaciones es: {medico_critico['nombre'].values}")

Total de turnos cancelados o ausentes: 51
El médico con más cancelaciones es: <StringArray>
['Dra. Beatriz Sosa']
Length: 1, dtype: str

### 6) Reporte final

Escriban un bloque de código que imprima un reporte con los resultados de los cuatro puntos anteriores, en formato legible. No es necesario que sea elaborado — lo importante es que quede claro qué encontraron.

In [ ]:
print("=" * 50)
print("REPORTE CLÍNICA MEDICARE")
print("=" * 50)

# tu reporte acá
# Punto 1: Actividad 
print("\n1. RANKING DE ACTIVIDAD POR MÉDICO:")
print(df_ranking_actividad.to_string(index=False))

# Punto 2: Facturación 
print("\n2. FACTURACIÓN TOTAL POR ESPECIALIDAD:")
print(df_facturacion_especialidad.to_string(index=False))

# PUNTO 3: Obras Sociales 

conteo_obras = df_pacientes_limpio['obra_social'].value_counts()

print(f"Obra social con más pacientes: {conteo_obras.idxmax()}")
print(f"Pacientes sin obra social: {conteo_obras.get('Sin Obra Social', 0)}")

# PUNTO 4: Ausentismo 
print(f"Total de turnos cancelados o ausentes: {total_no_concretados}")
print(f"El médico con más cancelaciones es: {medico_critico['nombre'].values}")

print("\n" + "=" * 50)
print("FIN DEL REPORTE")
print("=" * 50)

==================================================
REPORTE CLÍNICA MEDICARE
==================================================

1. RANKING DE ACTIVIDAD POR MÉDICO:
             nombre  cantidad_turnos
  Dra. Beatriz Sosa               34
 Dr. Sebastián Ríos               31
Dra. Carmen Aguirre               28
   Dr. Pablo Méndez               18
   Dr. Nicolás Vera               18
  Dra. Silvina Vega               13
 Dra. Laura Giménez               13
 Dra. Gabriela Luna               11
 Dra. Andrea Blanco               11
 Dr. Ezequiel Bravo               10
   Dr. Martín Cufré                9
   Dr. Hernán Costa                9
  Dra. Verónica Paz                5

2. FACTURACIÓN TOTAL POR ESPECIALIDAD:
  especialidad  total_facturado
   Cardiología         100800.0
  Dermatología         100300.0
 Traumatología          98700.0
Clínica Médica          75500.0
     Pediatría          75400.0
   Psiquiatría          41000.0
   Ginecología          26600.0
Endocrinología          24700.0
    Neurología          11000.0
Obra social con más pacientes: Sin Obra Social
Pacientes sin obra social: 12
Total de turnos cancelados o ausentes: 51
El médico con más cancelaciones es: <StringArray>
['Dra. Beatriz Sosa']
Length: 1, dtype: str

==================================================
FIN DEL REPORTE
==================================================

→ [Ir a la solución](./solucion.md)